" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry

set nocompatible
filetype plugin indent on

set noswapfile
set number
set noro
set ic

syntax on

call plug#begin('~/.vim_runtime/plugged')
  Plug 'towolf/vim-helm'
  Plug 'vim-ruby/vim-ruby'
call plug#end()
